//********************************************************************
//*    
//* Warning: This file was generated by ecore4CPP Generator
//*
//********************************************************************

#ifndef LIBRARYMODEL_ECORE_AUTHOR_HPP
#define LIBRARYMODEL_ECORE_AUTHOR_HPP


#include <memory>
#include <string>
// forward declarations


//*********************************
// generated Includes
#include <map> // used for Persistence
#include <vector> // used for Persistence
namespace persistence
{
	namespace interfaces
	{
		class XLoadHandler; // used for Persistence
		class XSaveHandler; // used for Persistence
	}
}

namespace libraryModel_ecore
{
	class libraryModel_ecoreFactory;
}

//Forward Declaration for used types 
namespace libraryModel_ecore 
{
	class LibraryModel;
}

// namespace macro header include
#include "libraryModel_ecore/libraryModel_ecore.hpp"

// base class includes
#include "libraryModel_ecore/NamedElement.hpp"




//*********************************
namespace libraryModel_ecore 
{
	
	class LIBRARYMODEL_ECORE_API Author : virtual public NamedElement
	{
		public:
 			Author(const Author &) {}

		protected:
			Author(){}
			//Additional constructors for the containments back reference
			Author(std::weak_ptr<libraryModel_ecore::LibraryModel> par_library);

		public:
			virtual std::shared_ptr<ecore::EObject> copy() const = 0;

			//destructor
			virtual ~Author() {}

			//*********************************
			// Operations
			//*********************************

			//*********************************
			// Attribute Getters & Setters
			//*********************************

			//*********************************
			// Reference Getters & Setters
			//*********************************
			virtual std::weak_ptr<libraryModel_ecore::LibraryModel> getLibrary() const = 0;
			virtual void setLibrary(std::weak_ptr<libraryModel_ecore::LibraryModel>) = 0;

			//*********************************
			// Union Reference Getters
			//*********************************

			//*********************************
			// Container Getter
			//*********************************
			virtual std::shared_ptr<ecore::EObject> eContainer() const = 0; 

			//*********************************
			// Persistence Functions
			//*********************************
			virtual void load(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler) = 0;
			virtual void resolveReferences(const int featureID, std::vector<std::shared_ptr<ecore::EObject> > references) = 0;
			virtual void save(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const = 0;

		protected:
			//*********************************
			// Attribute Members
			//*********************************
			
			//*********************************
			// Reference Members
			//*********************************
			std::weak_ptr<libraryModel_ecore::LibraryModel> m_library;
	};
}
#endif /* end of include guard: LIBRARYMODEL_ECORE_AUTHOR_HPP */
