//********************************************************************
//*    
//* Warning: This file was generated by ecore4CPP Generator
//*
//********************************************************************

#ifndef LIBRARYMODEL_ECORE_LIBRARYMODEL_HPP
#define LIBRARYMODEL_ECORE_LIBRARYMODEL_HPP


#include <memory>
#include <string>
// forward declarations
template<class T> class Bag; 


//*********************************
// generated Includes
#include <map> // used for Persistence
#include <vector> // used for Persistence
namespace persistence
{
	namespace interfaces
	{
		class XLoadHandler; // used for Persistence
		class XSaveHandler; // used for Persistence
	}
}

namespace libraryModel_ecore
{
	class libraryModel_ecoreFactory;
}

//Forward Declaration for used types 
namespace libraryModel_ecore 
{
	class Author;
	class Book;
}

// namespace macro header include
#include "libraryModel_ecore/libraryModel_ecore.hpp"



#include "ecore/EModelElement.hpp"


//*********************************
namespace libraryModel_ecore 
{
	
	class LIBRARYMODEL_ECORE_API LibraryModel : virtual public ecore::EModelElement
	{
		public:
 			LibraryModel(const LibraryModel &) {}

		protected:
			LibraryModel(){}

		public:
			virtual std::shared_ptr<ecore::EObject> copy() const = 0;

			//destructor
			virtual ~LibraryModel() {}

			//*********************************
			// Operations
			//*********************************
			virtual void printLibrary() = 0;

			//*********************************
			// Attribute Getters & Setters
			//*********************************

			//*********************************
			// Reference Getters & Setters
			//*********************************
			virtual std::shared_ptr<Bag<libraryModel_ecore::Author>> getAuthors() const = 0;
			virtual std::shared_ptr<Bag<libraryModel_ecore::Book>> getBook() const = 0;

			//*********************************
			// Union Reference Getters
			//*********************************

			//*********************************
			// Container Getter
			//*********************************
			virtual std::shared_ptr<ecore::EObject> eContainer() const = 0; 

			//*********************************
			// Persistence Functions
			//*********************************
			virtual void load(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler) = 0;
			virtual void resolveReferences(const int featureID, std::vector<std::shared_ptr<ecore::EObject> > references) = 0;
			virtual void save(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const = 0;

		protected:
			//*********************************
			// Attribute Members
			//*********************************
			
			//*********************************
			// Reference Members
			//*********************************
			mutable std::shared_ptr<Bag<libraryModel_ecore::Author>> m_authors;
			mutable std::shared_ptr<Bag<libraryModel_ecore::Book>> m_book;
	};
}
#endif /* end of include guard: LIBRARYMODEL_ECORE_LIBRARYMODEL_HPP */
