// DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN
// generated by ecore4cpp::generator::main::generatePackageHeaderFile

#ifndef __libraryModel_ecore_libraryModel_ecore_hpp
#define __libraryModel_ecore_libraryModel_ecore_hpp

#ifdef _MSC_VER
#pragma once
#endif //_MSC_VER

#if defined(WIN32) || defined(_WIN32) || defined(__WIN32__) || defined(__NT__)
  #if defined(BUILD_LIBRARYMODEL_ECORE)
    #define LIBRARYMODEL_ECORE_API __declspec(dllexport)
  #else
    #define LIBRARYMODEL_ECORE_API __declspec(dllimport)
  #endif
#else
  #define LIBRARYMODEL_ECORE_API 
#endif

#endif //__libraryModel_ecore_libraryModel_ecore_hpp

//EOF
