//********************************************************************
//*    
//* Warning: This file was generated by ecore4CPP Generator
//*
//********************************************************************

#ifndef LIBRARYMODEL_ECORE_AUTHORAUTHORIMPL_HPP
#define LIBRARYMODEL_ECORE_AUTHORAUTHORIMPL_HPP

//*********************************
// generated Includes

// namespace macro header include
#include "libraryModel_ecore/libraryModel_ecore.hpp" 

// model includes
#include "../Author.hpp"

#include "libraryModel_ecore/impl/NamedElementImpl.hpp"

//*********************************
namespace libraryModel_ecore 
{
	class LIBRARYMODEL_ECORE_API AuthorImpl : virtual public NamedElementImpl, virtual public Author 
	{
		public: 
			AuthorImpl(const AuthorImpl & obj);
			virtual std::shared_ptr<ecore::EObject> copy() const;
			AuthorImpl& operator=(AuthorImpl const&); 

		protected:
			friend class libraryModel_ecoreFactoryImpl;
			AuthorImpl();
			virtual std::shared_ptr<libraryModel_ecore::Author> getThisAuthorPtr() const;
			virtual void setThisAuthorPtr(std::weak_ptr<libraryModel_ecore::Author> thisAuthorPtr);

			//Additional constructors for the containments back reference
			AuthorImpl(std::weak_ptr<libraryModel_ecore::LibraryModel> par_library);

		public:
			//destructor
			virtual ~AuthorImpl();
			
			//*********************************
			// Operations
			//*********************************
			
			//*********************************
			// Attribute Getters & Setters
			//*********************************
			
			//*********************************
			// Reference Getters & Setters
			//*********************************
			virtual std::weak_ptr<libraryModel_ecore::LibraryModel> getLibrary() const ;
			virtual void setLibrary(std::weak_ptr<libraryModel_ecore::LibraryModel>) ;
			
			//*********************************
			// Union Reference Getters
			//*********************************
			
			//*********************************
			// Container Getter
			//*********************************
			virtual std::shared_ptr<ecore::EObject> eContainer() const ; 

			//*********************************
			// Persistence Functions
			//*********************************
			virtual void load(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler) ;
			virtual void loadAttributes(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler, std::map<std::string, std::string> attr_list);
			virtual void loadNode(std::string nodeName, std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler);
			virtual void resolveReferences(const int featureID, std::vector<std::shared_ptr<ecore::EObject> > references) ;
			virtual void save(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const ;
			virtual void saveContent(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const;

		protected:
			virtual std::shared_ptr<ecore::EClass> eStaticClass() const;

			//*********************************
			// EStructuralFeature Get/Set/IsSet
			//*********************************
			virtual std::shared_ptr<Any> eGet(int featureID, bool resolve, bool coreType) const ;
			virtual bool eSet(int featureID, std::shared_ptr<Any> newValue) ;
			virtual bool internalEIsSet(int featureID) const ;

			//*********************************
			// EOperation Invoke
			//*********************************
			virtual std::shared_ptr<Any> eInvoke(int operationID, std::shared_ptr<Bag<Any>> arguments) ;

		private:
			std::weak_ptr<libraryModel_ecore::Author> m_thisAuthorPtr;
	};
}
#endif /* end of include guard: LIBRARYMODEL_ECORE_AUTHORAUTHORIMPL_HPP */
