//********************************************************************
//*    
//* Warning: This file was generated by ecore4CPP Generator
//*
//********************************************************************

#ifndef LIBRARYMODEL_ECOREPLUGINIMPL_HPP
#define LIBRARYMODEL_ECOREPLUGINIMPL_HPP

// namespace macro header include
#include "libraryModel_ecore/libraryModel_ecore.hpp"

#include "libraryModel_ecore/libraryModel_ecorePlugin.hpp"

namespace libraryModel_ecore 
{
	class LIBRARYMODEL_ECORE_API libraryModel_ecorePluginImpl : virtual public libraryModel_ecorePlugin 
	{
		public:
			libraryModel_ecorePluginImpl();
			virtual ~libraryModel_ecorePluginImpl();
		
			virtual std::string eclipseURI();
			virtual std::string eNAME();
			virtual std::string eNS_URI();
			virtual std::string eNS_PREFIX();
		
			virtual std::shared_ptr<ecore::EObject> create(const std::string& name) const;
			virtual std::shared_ptr<ecore::EObject> create(const std::string& name, std::shared_ptr<ecore::EObject> container, const unsigned int referenceID = -1) const;
			virtual std::shared_ptr<ecore::EFactory> getEFactory();
			virtual std::shared_ptr<ecore::EPackage> getEPackage();
	};
}
#endif /* end of include guard: LIBRARYMODEL_ECOREPLUGINIMPL_HPP */
