//********************************************************************
//*    
//* Warning: This file was generated by ecore4CPP Generator
//*
//********************************************************************

#ifndef LIBRARYMODEL_ECORE_PICTUREPICTUREIMPL_HPP
#define LIBRARYMODEL_ECORE_PICTUREPICTUREIMPL_HPP

//*********************************
// generated Includes

// namespace macro header include
#include "libraryModel_ecore/libraryModel_ecore.hpp" 

// model includes
#include "../Picture.hpp"

#include "libraryModel_ecore/impl/NamedElementImpl.hpp"

//*********************************
namespace libraryModel_ecore 
{
	class LIBRARYMODEL_ECORE_API PictureImpl : virtual public NamedElementImpl, virtual public Picture 
	{
		public: 
			PictureImpl(const PictureImpl & obj);
			virtual std::shared_ptr<ecore::EObject> copy() const;
			PictureImpl& operator=(PictureImpl const&); 

		protected:
			friend class libraryModel_ecoreFactoryImpl;
			PictureImpl();
			virtual std::shared_ptr<libraryModel_ecore::Picture> getThisPicturePtr() const;
			virtual void setThisPicturePtr(std::weak_ptr<libraryModel_ecore::Picture> thisPicturePtr);

			//Additional constructors for the containments back reference
			PictureImpl(std::weak_ptr<libraryModel_ecore::Book> par_book);

		public:
			//destructor
			virtual ~PictureImpl();
			
			//*********************************
			// Operations
			//*********************************
			
			//*********************************
			// Attribute Getters & Setters
			//*********************************
			virtual int getPageNumber() const ;
			virtual void setPageNumber (int _pageNumber);
			
			//*********************************
			// Reference Getters & Setters
			//*********************************
			virtual std::weak_ptr<libraryModel_ecore::Book> getBook() const ;
			virtual void setBook(std::weak_ptr<libraryModel_ecore::Book>) ;
			
			//*********************************
			// Union Reference Getters
			//*********************************
			
			//*********************************
			// Container Getter
			//*********************************
			virtual std::shared_ptr<ecore::EObject> eContainer() const ; 

			//*********************************
			// Persistence Functions
			//*********************************
			virtual void load(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler) ;
			virtual void loadAttributes(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler, std::map<std::string, std::string> attr_list);
			virtual void loadNode(std::string nodeName, std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler);
			virtual void resolveReferences(const int featureID, std::vector<std::shared_ptr<ecore::EObject> > references) ;
			virtual void save(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const ;
			virtual void saveContent(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const;

		protected:
			virtual std::shared_ptr<ecore::EClass> eStaticClass() const;

			//*********************************
			// EStructuralFeature Get/Set/IsSet
			//*********************************
			virtual std::shared_ptr<Any> eGet(int featureID, bool resolve, bool coreType) const ;
			virtual bool eSet(int featureID, std::shared_ptr<Any> newValue) ;
			virtual bool internalEIsSet(int featureID) const ;

			//*********************************
			// EOperation Invoke
			//*********************************
			virtual std::shared_ptr<Any> eInvoke(int operationID, std::shared_ptr<Bag<Any>> arguments) ;

		private:
			std::weak_ptr<libraryModel_ecore::Picture> m_thisPicturePtr;
	};
}
#endif /* end of include guard: LIBRARYMODEL_ECORE_PICTUREPICTUREIMPL_HPP */
